[package]
name = "rusty"
version = "0.1.0"
authors = ["Haxeil <lezharayman@gmail.com>"]
edition = "2018"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
gdnative = "0.10.0"
bevy_ecs = "0.7.0"
